# Generated by Django 5.2 on 2025-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escola_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professores',
            name='disciplinas',
            field=models.CharField(max_length=30),
        ),
    ]
