# Generated by Django 5.2 on 2025-05-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Escola_app', '0002_alter_professores_disciplinas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professores',
            old_name='disciplinas',
            new_name='disciplina',
        ),
    ]
