# Generated by Django 5.2 on 2025-05-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escola_app', '0003_rename_disciplinas_professores_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professores',
            name='dataContratacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='professores',
            name='dataNascimento',
            field=models.DateField(),
        ),
    ]
